replicaCount: 2

image:
  repository: gcr.io/my-project/api-service
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.example.com
      paths: ["/"]
  tls:
    - secretName: api-tls
      hosts:
        - api.example.com